site_name: GDD - Purrfect Kitten

extra_css:
  - css/purrfect-toc.css

theme:
  name: null
  custom_dir: mkdocs_dracula_theme
  favicon: images/Moninha.png   # ğŸ‘ˆ agora seu site vai usar o gatinho!

nav:
  - InÃ­cio: index.md
