site_name: GDD - Purrfect Kitten

theme:
  name: null
  custom_dir: mkdocs_dracula_theme

nav:
  - Início: index.md  # se o GDD estiver no index.md
  # ou, se você criar um gdd.md separado:
  # - GDD Completo: gdd.md


